function App() {
    return (
          <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-black text-white">
                <div className="container mx-auto px-4 py-16">
                        <header className="text-center mb-16">
                                  <h1 className="text-5xl md:text-7xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-purple-500">
                                              Site Factory v4
                                  </h1>h1>
                                  <p className="text-xl md:text-2xl text-gray-300">
                                              One-Shot Site Factory - React + Tailwind CSS
                                  </p>p>
                        </header>header>
                        
                        <main className="max-w-4xl mx-auto">
                                  <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 shadow-2xl border border-white/20">
                                              <h2 className="text-2xl font-semibold mb-4 text-cyan-400">
                                                            Welcome to Site Factory
                                              </h2>h2>
                                              <p className="text-gray-300 leading-relaxed">
                                                            This is a template site generated by the One-Shot Site Factory system.
                                                            Your custom content will appear here once the automation workflow processes your document.
                                              </p>p>
                                  </div>div>
                        </main>main>
                        
                        <footer className="text-center mt-16 text-gray-500">
                                  <p>Powered by One-Shot Site Factory</p>p>
                        </footer>footer>
                </div>div>
          </div>div>
        )
}

export default App</div>
